function [scenario, egoVehicle] = createDrivingScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.13 (R2022b) and Automated Driving Toolbox 3.6 (R2022b).
% Generated on: 28-Feb-2023 18:10:36

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [50.0 10.0 0;
               0 10.0 0];
road(scenario, roadCenters, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [5 10 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [5 10 0;
            50 10 0];

speed = [30;30];
trajectory(egoVehicle, waypoints, speed);

